import type {Metadata} from "next";
import {ReactNode} from "react";
import '../app/index.scss';
export const metadata: Metadata = {
  title: "A-Todolist-n",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body>{children}</body>
    </html>
  );
}
